apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-image-data
  namespace: mokelumne
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-product-data
  namespace: mokelumne
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
