version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - PORT=3000
    volumes:
      - ./services/product-service:/app
      - /app/node_modules

volumes:
  mongo-data:
