apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-user
  namespace: mokelumne
spec:
  serviceName: mongo-user
  replicas: 1
  selector:
    matchLabels:
      app: mongo-user
  template:
    metadata:
      labels:
        app: mongo-user
    spec:
      containers:
      - name: mongo
        image: mongo:7
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_DATABASE
          value: mokelumne
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-user
  namespace: mokelumne
spec:
  selector:
    app: mongo-user
  ports:
    - port: 27017
      targetPort: 27017
