apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-product
  namespace: mokelumne
spec:
  serviceName: mongo-product
  replicas: 1
  selector:
    matchLabels:
      app: mongo-product
  template:
    metadata:
      labels:
        app: mongo-product
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-product
  namespace: mokelumne
spec:
  selector:
    app: mongo-product
  ports:
  - port: 27017
    targetPort: 27017
