apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: mokelumne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: cart-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-cart:27017
        envFrom:
        - secretRef:
            name: firebase-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: mokelumne
spec:
  selector:
    app: cart-service
  ports:
  - port: 3000
    targetPort: 3000
