apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: mokelumne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
      - name: image-service
        image: image-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-image:27017
        - name: PORT
          value: "4000"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        envFrom:
          - secretRef:
              name: firebase-secret
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: image-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
  namespace: mokelumne
spec:
  selector:
    app: image-service
  ports:
  - port: 4000
    targetPort: 4000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-uploads-pvc
  namespace: mokelumne
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
