apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: mokelumne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_URI
            value: mongodb://mongo-order:27017
          - name: WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: webhook-secret
                key: WEBHOOK_SECRET
          - name: INTERNAL_SECRET # Hinzugefügter Secret-Verweis
            valueFrom:
              secretKeyRef:
                name: internal-secret # Name des erstellten Secrets
                key: INTERNAL_SECRET
        envFrom:
          - secretRef:
              name: firebase-secret

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: mokelumne
spec:
  selector:
    app: order-service
  ports:
  - port: 3000
    targetPort: 3000
