apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: mokelumne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-product:27017
        - name: PORT
          value: "3000"
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: mokelumne
spec:
  selector:
    app: product-service
  ports:
  - port: 3000
    targetPort: 3000
